### ISSUE TITLE
Fixed composition in ternary alloy changes during calculation

### ISSUE THREAD

**Issue by jlaehne** [Aurelien354/BadgerFilm#3]
We have been fitting data of a ternary III-nitride alloy on top of a binary III-nitride substrate. Fixing the composition of the binary substrate to its stochiometry (0.5/0.5 at %) works well. For the ternary alloy, we also want to fix the stochiometry of N to 0.5. We mark it as fixed through a right click (blue background), but after the calculation the N-content is always changed to a higher value than stochiometry (0.55-0.57). Actually, the deviation from stochiometry is even slightly lower when we do not fix the N-content. I would expect the program to only fit the concentrations of the group-III elements, but to keep the value for N.

**Comment by Aurelien354** [comment]
Thank you for letting us know of this bug.
The atomic fractions were not properly normalized when the values were entered manually in the cells.
This improper normalization was only visible for fixed values and after the fitting calculations when the atomic fractions were displayed as normalized values.
This bug is now fixed in the latest version of BadgerFilm (1.2.20).
Thank you again for finding this error.

Best,
Aurélien

**Comment by jlaehne** [comment]
Thanks for fixing it so quickly, we'll try it out tomorrow.

**Comment by jlaehne** [comment]
Hi Aurélien,

it still does not behave quite as I expect it. I enter the expected values and fix N to 0.5:

![Locked_N](https://user-images.githubusercontent.com/7076057/190408823-8f9179e1-c59f-40aa-afb6-a325adf61e25.PNG)

After running the calculation, the N value is changed, while I would have expected it to stay at 0.5 and only the other two values to be normalized to the remaining 0.5:

![Locked_N_result](https://user-images.githubusercontent.com/7076057/190408832-da1d04ac-3ea8-4ab4-8f2e-bf1c058d49f0.PNG)

Best,
Jonas

**Comment by Aurelien354** [comment]
Hi Jonas,

Thank you for providing more details. I do understand now where the problem is coming from.

The fitting algorithm uses a so-called phi-rho-Z model to calculate the different concentrations and the layer thickness.
To perform the calculations, the model uses concentrations defined in weight fraction, not in atomic fraction. This is where the problem is coming from: your nitrogen concentration was fixed and unchanged by the fitting algorithm when expressed in wt. fraction, but not when converted into an at. fraction (because this conversion takes into account the concentrations of all the elements present in the layer, which have been changed between the initial value and the final value).
To solve this, I forced the algorithm to recalculate the nitrogen wt. fraction value, at each iteration of the fitting process, to keep the fixed at. fraction.

Note, this is only working when only one single element has its concentration fixed (and the layer concentrations are defined in atomic fraction).
When, in the same layer, two or more elements have their concentrations fixed (and the layer concentrations are defined in atomic fraction), because changing the wt. fraction of one element (to ensure the at. fraction is correct) will change the atomic fraction of the other elements, the returned atomic fractions may not be correct.
It seems that clicking multiple times on the Calculate button (while waiting for the program to finish the calculations and readjusting the known at. fractions in between each click) will make the concentrations converge to a value. However, I would need to test this more extensively to be sure it is the correct value. It is also very impractical as it is now and I would need to automate it.

The changes have been implemented in version 1.2.21.

Please let me know if this is solving your problem.

Best,
Aurélien

**Comment by jlaehne** [comment]
Hi Aurélien,

thanks also for the explanation. We'll test it and give you feedback in the next days :-)

Best,
Jonas

**Comment by jlaehne** [comment]
Looks good now! Thanks.
